# Generated by Django 5.2.4 on 2025-08-01 04:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_inr', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Price in Indian Rupees (INR)', max_digits=8, null=True)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, help_text='URL for the book cover image', max_length=500, null=True)),
                ('is_trending', models.BooleanField(default=False)),
                ('published_year', models.PositiveIntegerField(blank=True, help_text='Year the book was published', null=True)),
            ],
        ),
    ]
